CREATE TABLE PRODUCTS(
    ID SERIAL NOT NULL PRIMARY KEY,
    MANUFACTURER_NAME TEXT NOT NULL,
    MODEL_NAME TEXT NOT NULL,
    PRICE DECIMAL NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0
);

CREATE TABLE USERS(
    ID SERIAL NOT NULL PRIMARY KEY,
    USERNAME TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    ROLE TEXT NOT NULL
)
